[package]
name = "tree-sitter-nim"
version = "0.1.0"
description = "Nim grammar for tree-sitter"
repository = "https://github.com/undivisible/tree-sitter-nim"
license = "MIT"
edition = "2021"
build = "bindings/rust/build.rs"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.0"
