/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_proc = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_func = 4,
  anon_sym_LPAREN = 5,
  aux_sym_parameters_token1 = 6,
  anon_sym_RPAREN = 7,
  aux_sym_type_token1 = 8,
  aux_sym__statement_token1 = 9,
  sym_source_file = 10,
  sym_proc_declaration = 11,
  sym_func_declaration = 12,
  sym_parameters = 13,
  sym_type = 14,
  sym_identifier = 15,
  sym_body = 16,
  sym__statement = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_parameters_repeat1 = 19,
  aux_sym_body_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_proc] = "proc",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [aux_sym_parameters_token1] = "parameters_token1",
  [anon_sym_RPAREN] = ")",
  [aux_sym_type_token1] = "type_token1",
  [aux_sym__statement_token1] = "_statement_token1",
  [sym_source_file] = "source_file",
  [sym_proc_declaration] = "proc_declaration",
  [sym_func_declaration] = "func_declaration",
  [sym_parameters] = "parameters",
  [sym_type] = "type",
  [sym_identifier] = "identifier",
  [sym_body] = "body",
  [sym__statement] = "_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_proc] = anon_sym_proc,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_parameters_token1] = aux_sym_parameters_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_type_token1] = aux_sym_type_token1,
  [aux_sym__statement_token1] = aux_sym__statement_token1,
  [sym_source_file] = sym_source_file,
  [sym_proc_declaration] = sym_proc_declaration,
  [sym_func_declaration] = sym_func_declaration,
  [sym_parameters] = sym_parameters,
  [sym_type] = sym_type,
  [sym_identifier] = sym_identifier,
  [sym_body] = sym_body,
  [sym__statement] = sym__statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_proc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_parameters_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_type_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_proc_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_func_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_parameters = 3,
  field_return_type = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_name, 1},
  [2] =
    {field_body, 4},
    {field_name, 1},
    {field_parameters, 2},
  [5] =
    {field_body, 5},
    {field_name, 1},
    {field_return_type, 3},
  [8] =
    {field_body, 6},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 9,
  [26] = 12,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 31,
  [34] = 34,
  [35] = 35,
  [36] = 30,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'p') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 2:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'p') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_proc);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_parameters_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_parameters_token1);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == 'c') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == 'c') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == 'n') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == 'o') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == 'r') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == 'u') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__statement_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          (lookahead < '0' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_proc] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_type_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym_proc_declaration] = STATE(2),
    [sym_func_declaration] = STATE(2),
    [sym__statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_proc] = ACTIONS(5),
    [anon_sym_func] = ACTIONS(7),
    [aux_sym_type_token1] = ACTIONS(9),
    [aux_sym__statement_token1] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_proc,
    ACTIONS(7), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      aux_sym_type_token1,
    ACTIONS(17), 1,
      aux_sym__statement_token1,
    STATE(3), 4,
      sym_proc_declaration,
      sym_func_declaration,
      sym__statement,
      aux_sym_source_file_repeat1,
  [22] = 6,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_proc,
    ACTIONS(24), 1,
      anon_sym_func,
    ACTIONS(27), 1,
      aux_sym_type_token1,
    ACTIONS(30), 1,
      aux_sym__statement_token1,
    STATE(3), 4,
      sym_proc_declaration,
      sym_func_declaration,
      sym__statement,
      aux_sym_source_file_repeat1,
  [44] = 5,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      aux_sym_type_token1,
    ACTIONS(39), 1,
      aux_sym__statement_token1,
    ACTIONS(35), 2,
      anon_sym_proc,
      anon_sym_func,
    STATE(5), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [62] = 5,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      aux_sym_type_token1,
    ACTIONS(48), 1,
      aux_sym__statement_token1,
    ACTIONS(43), 2,
      anon_sym_proc,
      anon_sym_func,
    STATE(5), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [80] = 2,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(53), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [90] = 3,
    STATE(14), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [102] = 3,
    STATE(11), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [114] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      aux_sym_parameters_token1,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    STATE(12), 2,
      sym_parameters,
      aux_sym_parameters_repeat1,
  [128] = 3,
    STATE(19), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [140] = 2,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(65), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [150] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      aux_sym_parameters_token1,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(16), 2,
      sym_parameters,
      aux_sym_parameters_repeat1,
  [164] = 3,
    STATE(17), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [176] = 2,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(73), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [186] = 3,
    STATE(20), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [198] = 4,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      aux_sym_parameters_token1,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(16), 2,
      sym_parameters,
      aux_sym_parameters_repeat1,
  [212] = 2,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(85), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [222] = 3,
    STATE(22), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [234] = 2,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(89), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [244] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(93), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [254] = 3,
    STATE(6), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [266] = 2,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(97), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [276] = 3,
    STATE(24), 1,
      sym_body,
    ACTIONS(55), 2,
      aux_sym_type_token1,
      aux_sym__statement_token1,
    STATE(4), 2,
      sym__statement,
      aux_sym_body_repeat1,
  [288] = 2,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      aux_sym__statement_token1,
    ACTIONS(101), 3,
      anon_sym_proc,
      anon_sym_func,
      aux_sym_type_token1,
  [298] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      aux_sym_parameters_token1,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    STATE(26), 2,
      sym_parameters,
      aux_sym_parameters_repeat1,
  [312] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      aux_sym_parameters_token1,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    STATE(16), 2,
      sym_parameters,
      aux_sym_parameters_repeat1,
  [326] = 4,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    STATE(41), 1,
      sym_parameters,
  [339] = 4,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_COLON,
    ACTIONS(117), 1,
      anon_sym_EQ,
    STATE(35), 1,
      sym_parameters,
  [352] = 1,
    ACTIONS(119), 3,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_LPAREN,
  [358] = 2,
    ACTIONS(123), 1,
      aux_sym_parameters_token1,
    ACTIONS(121), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [366] = 2,
    ACTIONS(127), 1,
      aux_sym_parameters_token1,
    ACTIONS(125), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [374] = 2,
    ACTIONS(129), 1,
      aux_sym_type_token1,
    STATE(28), 1,
      sym_identifier,
  [381] = 1,
    ACTIONS(127), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [386] = 2,
    ACTIONS(131), 1,
      aux_sym_type_token1,
    STATE(42), 1,
      sym_type,
  [393] = 2,
    ACTIONS(133), 1,
      anon_sym_COLON,
    ACTIONS(135), 1,
      anon_sym_EQ,
  [400] = 1,
    ACTIONS(123), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [405] = 2,
    ACTIONS(131), 1,
      aux_sym_type_token1,
    STATE(45), 1,
      sym_type,
  [412] = 2,
    ACTIONS(129), 1,
      aux_sym_type_token1,
    STATE(27), 1,
      sym_identifier,
  [419] = 2,
    ACTIONS(131), 1,
      aux_sym_type_token1,
    STATE(46), 1,
      sym_type,
  [426] = 2,
    ACTIONS(131), 1,
      aux_sym_type_token1,
    STATE(43), 1,
      sym_type,
  [433] = 2,
    ACTIONS(137), 1,
      anon_sym_COLON,
    ACTIONS(139), 1,
      anon_sym_EQ,
  [440] = 1,
    ACTIONS(141), 1,
      anon_sym_EQ,
  [444] = 1,
    ACTIONS(143), 1,
      anon_sym_EQ,
  [448] = 1,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
  [452] = 1,
    ACTIONS(147), 1,
      anon_sym_EQ,
  [456] = 1,
    ACTIONS(149), 1,
      anon_sym_EQ,
  [460] = 1,
    ACTIONS(151), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 90,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 114,
  [SMALL_STATE(10)] = 128,
  [SMALL_STATE(11)] = 140,
  [SMALL_STATE(12)] = 150,
  [SMALL_STATE(13)] = 164,
  [SMALL_STATE(14)] = 176,
  [SMALL_STATE(15)] = 186,
  [SMALL_STATE(16)] = 198,
  [SMALL_STATE(17)] = 212,
  [SMALL_STATE(18)] = 222,
  [SMALL_STATE(19)] = 234,
  [SMALL_STATE(20)] = 244,
  [SMALL_STATE(21)] = 254,
  [SMALL_STATE(22)] = 266,
  [SMALL_STATE(23)] = 276,
  [SMALL_STATE(24)] = 288,
  [SMALL_STATE(25)] = 298,
  [SMALL_STATE(26)] = 312,
  [SMALL_STATE(27)] = 326,
  [SMALL_STATE(28)] = 339,
  [SMALL_STATE(29)] = 352,
  [SMALL_STATE(30)] = 358,
  [SMALL_STATE(31)] = 366,
  [SMALL_STATE(32)] = 374,
  [SMALL_STATE(33)] = 381,
  [SMALL_STATE(34)] = 386,
  [SMALL_STATE(35)] = 393,
  [SMALL_STATE(36)] = 400,
  [SMALL_STATE(37)] = 405,
  [SMALL_STATE(38)] = 412,
  [SMALL_STATE(39)] = 419,
  [SMALL_STATE(40)] = 426,
  [SMALL_STATE(41)] = 433,
  [SMALL_STATE(42)] = 440,
  [SMALL_STATE(43)] = 444,
  [SMALL_STATE(44)] = 448,
  [SMALL_STATE(45)] = 452,
  [SMALL_STATE(46)] = 456,
  [SMALL_STATE(47)] = 460,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_declaration, 7, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_proc_declaration, 7, 0, 4),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_declaration, 4, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_proc_declaration, 4, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_declaration, 4, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_declaration, 4, 0, 1),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_declaration, 5, 0, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_proc_declaration, 5, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_declaration, 5, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_declaration, 5, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_declaration, 6, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_proc_declaration, 6, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_declaration, 6, 0, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_declaration, 6, 0, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_declaration, 7, 0, 4),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_declaration, 7, 0, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [145] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nim(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nim",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
